matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      env: ZSH_SRC=system
    - os: osx
      env: ZSH_SRC=homebrew
before_script:
- if [[ "$ZSH_SRC" == "homebrew" ]]; then brew install zsh; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install zsh; fi
- mkdir .bin
- sudo curl -L https://raw.githubusercontent.com/molovo/revolver/master/revolver > .bin/revolver
- sudo curl -L https://raw.githubusercontent.com/molovo/color/master/color.zsh > .bin/color
- chmod u+x .bin/{color,revolver}
- export PATH="$PWD/.bin:$PATH"
script: ./zunit
